---
baseurl:
languagecode: en-us
pluralizelisttitles: false
theme: hugo-blog-theme
title: The Forestry Blog
# menu:
#   managing_your_team:
#   - name: Adding Team Members
#     weight: 1
#   deployment_and_hosting:
#   - name: New page testing menu
#     weight: 3
#   getting_started:
#   - name: Support and help
#     weight: 3
#   setting_up_a_site:
#   - name: Setting up a site without hosting
#     weight: 3
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
